FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    ffmpeg \
    libopus-dev \
    libopus0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD ["python", "reactionspammer.py"]